version: '3.8'

services:
  aoostar-lcd:
    build: .
    container_name: aoostar-lcd
    restart: always
    ports:
      - "8765:8765"
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    volumes:
      - ./cfg:/app/cfg
      - ./webui.py:/app/webui.py
      - ./proxmox-sensors.sh:/app/proxmox-sensors.sh
    network_mode: host
    privileged: false
    environment:
      - PYTHONUNBUFFERED=1
