/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_pages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_settings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        DisplaySettings: {
            brand?: string;
            /** Format: int32 */
            brightness?: number;
            schedule?: components["schemas"]["ScheduleRule"][];
            schedule_enabled?: boolean;
            /** Format: int32 */
            switch_seconds?: number;
            timezone?: string;
        } & {
            [key: string]: unknown;
        };
        HealthDto: {
            ok: boolean;
            version: string;
        };
        PageSummaryDto: {
            /** Format: int32 */
            duration: number;
            enabled: boolean;
            id: string;
            name: string;
            /** Format: int64 */
            revision: number;
            template_id?: string | null;
        };
        PagesListDto: {
            carousel: string[];
            pages: components["schemas"]["PageSummaryDto"][];
            /** Format: int64 */
            revision: number;
            /** Format: int32 */
            schema_version: number;
        };
        PublicProviderDto: {
            enabled: boolean;
            node?: string | null;
            secret_set: boolean;
            system?: string | null;
            url: string;
            verify_tls: boolean;
        } & {
            [key: string]: unknown;
        };
        PublicSettingsDto: {
            display: components["schemas"]["DisplaySettings"];
            providers: {
                [key: string]: components["schemas"]["PublicProviderDto"];
            };
        } & {
            [key: string]: unknown;
        };
        ScheduleRule: {
            /** Format: int32 */
            brightness: number;
            end: string;
            start: string;
        } & {
            [key: string]: unknown;
        };
        StatusDto: {
            /** Format: int32 */
            brightness: number;
            device_present: boolean;
            native_brightness: boolean;
            /** Format: int64 */
            updated_unix?: number | null;
            version: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthDto"];
                };
            };
        };
    };
    get_pages: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagesListDto"];
                };
            };
        };
    };
    get_settings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicSettingsDto"];
                };
            };
        };
    };
    get_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusDto"];
                };
            };
        };
    };
}
