/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/display/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_capabilities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/display/luminance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["set_luminance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/display/power": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["set_power"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_metrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_pages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/providers/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_provider_catalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_settings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        DisplayCapabilitiesDto: {
            /** Format: int32 */
            height: number;
            native_brightness: boolean;
            power_control: boolean;
            power_on: boolean;
            /** Format: int32 */
            width: number;
        };
        DisplayLuminanceRequest: {
            /** Format: int32 */
            value: number;
        };
        DisplayPowerDto: {
            on: boolean;
        };
        DisplayPowerRequest: {
            on: boolean;
        };
        DisplaySettings: {
            brand?: string;
            /** Format: int32 */
            brightness?: number;
            schedule?: components["schemas"]["ScheduleRule"][];
            schedule_enabled?: boolean;
            /** Format: int32 */
            switch_seconds?: number;
            timezone?: string;
        } & {
            [key: string]: unknown;
        };
        HealthDto: {
            ok: boolean;
            version: string;
        };
        MetricCatalogDto: {
            metrics: components["schemas"]["MetricDescriptor"][];
        };
        MetricDescriptor: {
            category: string;
            demo_value?: unknown;
            id: string;
            label: string;
            /** Format: double */
            max?: number | null;
            /** Format: double */
            min?: number | null;
            online: boolean;
            provider_id: string;
            provider_name: string;
            recommended_widgets: components["schemas"]["WidgetKind"][];
            unit: string;
            value?: unknown;
            value_type: string;
        };
        PageSummaryDto: {
            /** Format: int32 */
            duration: number;
            enabled: boolean;
            id: string;
            name: string;
            /** Format: int64 */
            revision: number;
            template_id?: string | null;
        };
        PagesListDto: {
            carousel: string[];
            pages: components["schemas"]["PageSummaryDto"][];
            /** Format: int64 */
            revision: number;
            /** Format: int32 */
            schema_version: number;
        };
        ProviderCatalogDto: {
            providers: components["schemas"]["ProviderDescriptor"][];
        };
        ProviderDescriptor: {
            categories: string[];
            credential_fields: string[];
            icon: string;
            id: string;
            name: string;
        };
        PublicProviderDto: {
            enabled: boolean;
            node?: string | null;
            secret_set: boolean;
            system?: string | null;
            url: string;
            verify_tls: boolean;
        } & {
            [key: string]: unknown;
        };
        PublicSettingsDto: {
            display: components["schemas"]["DisplaySettings"];
            providers: {
                [key: string]: components["schemas"]["PublicProviderDto"];
            };
        } & {
            [key: string]: unknown;
        };
        ScheduleRule: {
            /** Format: int32 */
            brightness: number;
            end: string;
            start: string;
        } & {
            [key: string]: unknown;
        };
        StatusDto: {
            /** Format: int32 */
            brightness: number;
            device_present: boolean;
            native_brightness: boolean;
            /** Format: int64 */
            updated_unix?: number | null;
            version: string;
        };
        /** @enum {string} */
        WidgetKind: "text" | "value" | "bar" | "gauge" | "ring" | "badge" | "sparkline" | "image" | "animation";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_capabilities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DisplayCapabilitiesDto"];
                };
            };
        };
    };
    set_luminance: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DisplayLuminanceRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusDto"];
                };
            };
        };
    };
    set_power: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DisplayPowerRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DisplayPowerDto"];
                };
            };
        };
    };
    get_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthDto"];
                };
            };
        };
    };
    get_metrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricCatalogDto"];
                };
            };
        };
    };
    get_pages: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagesListDto"];
                };
            };
        };
    };
    get_provider_catalog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderCatalogDto"];
                };
            };
        };
    };
    get_settings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicSettingsDto"];
                };
            };
        };
    };
    get_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusDto"];
                };
            };
        };
    };
}
