<script lang="ts">
  import { onMount } from 'svelte';
  import { CANVAS_HEIGHT, CANVAS_WIDTH, clampRect, inversePointer, resizeRect, type Layer } from './model';
  let { layers, background = '#071019', selected, onselect, onchange }: { layers: Layer[]; background?: string; selected?: string; onselect: (id: string) => void; onchange: (id: string, changes: Partial<Layer>) => void } = $props();
  let host: HTMLDivElement; let canvas: HTMLDivElement; let scale = $state(1); let drag: { id: string; dx: number; dy: number; mode: 'move' | 'resize'; start?: Layer } | undefined;
  onMount(() => { const resize = () => { const rect = host.getBoundingClientRect(); scale = Math.min(Math.max(rect.width / CANVAS_WIDTH, 0.01), 1); }; const observer = new ResizeObserver(resize); observer.observe(host); resize(); return () => observer.disconnect(); });
  function move(event: PointerEvent) { if (!drag) return; const point = inversePointer(canvas.getBoundingClientRect(), event.clientX, event.clientY); const layer = layers.find((item) => item.id === drag?.id); if (!layer) return; onchange(layer.id, drag.mode === 'move' ? clampRect({ ...layer, x: point.x - drag.dx, y: point.y - drag.dy }) : resizeRect(drag.start ?? layer, { x: point.x - drag.dx, y: point.y - drag.dy })); }
  function start(event: PointerEvent, layer: Layer) { const point = inversePointer(canvas.getBoundingClientRect(), event.clientX, event.clientY); drag = { id: layer.id, dx: point.x - layer.x, dy: point.y - layer.y, mode: 'move' }; onselect(layer.id); (event.currentTarget as HTMLElement).setPointerCapture(event.pointerId); }
  function startResize(event: PointerEvent, layer: Layer) { event.stopPropagation(); const point = inversePointer(canvas.getBoundingClientRect(), event.clientX, event.clientY); drag = { id: layer.id, dx: point.x, dy: point.y, mode: 'resize', start: layer }; onselect(layer.id); (event.currentTarget as HTMLElement).setPointerCapture(event.pointerId); }
</script>
<div class="host" role="application" bind:this={host} onpointermove={move} onpointerup={() => drag = undefined} data-testid="canvas-host"><div class="canvas" bind:this={canvas} data-testid="logical-canvas" style={`width:${CANVAS_WIDTH}px;height:${CANVAS_HEIGHT}px;transform:scale(${scale});transform-origin:top left;background:${background}`}>
  {#each layers as layer (layer.id)}<div class:selected={layer.id === selected} class:badge={layer.type === 'badge'} class:gauge={layer.type === 'gauge' || layer.type === 'ring'} class:bar={layer.type === 'bar'} class="layer" role="button" tabindex="0" style={`left:${layer.x}px;top:${layer.y}px;width:${layer.width}px;height:${layer.height}px;z-index:${layer.z ?? 1};color:${layer.color ?? '#eaf8ff'};background:${String(layer.background_color ?? '')};border-color:${String(layer.border_color ?? '')};border-radius:${Number(layer.radius ?? 0)}px`} onpointerdown={(e) => start(e, layer)} onclick={() => onselect(layer.id)} onkeydown={(e) => e.key === 'Enter' && onselect(layer.id)}><span>{layer.text ?? layer.binding ?? layer.type}</span>{#if layer.id === selected}<span class="resize-handle" role="button" tabindex="0" aria-label={`Redimensionner ${layer.id}`} onpointerdown={(e) => startResize(e, layer)}></span>{/if}</div>{/each}
</div></div>
<style>.host{width:100%;overflow:hidden;aspect-ratio:960/376;background:#03090e;border-radius:12px;box-shadow:0 18px 55px #0008}.canvas{position:relative;box-shadow:0 0 0 1px #315363,inset 0 0 80px #00131f}.layer{position:absolute;display:grid;place-items:center;border:1px dashed transparent;color:inherit;overflow:hidden;font-weight:700;font-size:12px;text-align:center}.layer.badge{border-style:solid}.layer.gauge{border:12px solid currentColor!important;border-top-color:#1c2b3b!important;border-radius:50%!important;background:#0b1722}.layer.bar{background:linear-gradient(90deg,currentColor 0 68%,#1c2b3b 68%)!important;border-radius:999px!important}.layer.selected{outline:2px solid #5dd9ff;outline-offset:2px}.resize-handle{position:absolute;right:0;bottom:0;width:12px;height:12px;background:#5dd9ff;border:2px solid #071019;cursor:nwse-resize}</style>
