<script lang="ts">
  export type Preset = { id: string; name: string; source_asset_id: string; settings: { fps: number; speed_seconds: number } };
  export type Asset = { id: string; name: string; kind?: string; format?: string; revision?: number; width?: number; height?: number };
  let { assets = [], presets = [], onorbit, onpreview, onupload, onreplace, ondelete }: { assets?: Asset[]; presets?: Preset[]; onorbit: (sourceAssetId: string, displayName?: string) => void; onpreview: () => void; onupload?: (files: File[]) => void; onreplace?: (id: string, file: File) => void; ondelete?: (id: string) => void } = $props();
  let sourceAssetId = $state('');
  let displayName = $state('');
  let failedImages = $state(new Set<string>());
  const sourceFor = (preset: Preset) => assets.find((asset) => asset.id === preset.source_asset_id);
</script>
<section aria-label="Bibliothèque média">
  <div class="heading"><div><span>Assets</span><h2>Media Library</h2></div>{#if onupload}<label class="upload">Upload<input type="file" multiple hidden onchange={(event) => onupload?.([...(event.currentTarget.files ?? [])])} /></label>{/if}</div>
  <div class="library">{#each assets as asset}<article><div class="thumb">{#if asset.kind === 'image' && !failedImages.has(asset.id)}<img src={`/api/media/${asset.id}/file`} alt={asset.name} onerror={() => failedImages = new Set([...failedImages, asset.id])} />{:else}{asset.kind === 'image' ? '▧' : '▶'}{/if}</div><strong>{asset.name}</strong><small>{asset.format ?? 'asset'}{asset.width ? ` · ${asset.width}×${asset.height}` : ''} · r{asset.revision ?? 1}</small><div>{#if onreplace}<label>Replace<input type="file" hidden onchange={(event) => event.currentTarget.files?.[0] && onreplace?.(asset.id, event.currentTarget.files[0])} /></label>{/if}{#if ondelete}<button onclick={() => ondelete?.(asset.id)}>Delete</button>{/if}</div></article>{/each}</div>
  <div class="splash"><div class="splash-head"><div><span>Display media</span><h3>Splash animation</h3></div><button class="preview-button" onclick={onpreview} disabled={!presets.some((preset) => preset.id === 'orbit')}>Preview splash</button></div>
    <div class="preset-list">{#each presets as preset}{@const source = sourceFor(preset)}<article class="preset-card">
      <div class="preset-thumb">{#if source?.kind === 'image' && !failedImages.has(`preset-${source.id}`)}<img src={`/api/media/${source.id}/file`} alt={`Preview ${preset.name}`} onerror={() => failedImages = new Set([...failedImages, `preset-${source.id}`])} />{:else}<span>▧</span>{/if}</div>
      <div><strong>{preset.id === 'orbit' && preset.name === 'Orbit' ? 'Splash animation' : preset.name}</strong><small>{preset.settings.fps} FPS · {preset.settings.speed_seconds}s · {source?.name ?? 'source asset'}</small></div>
    </article>{/each}</div>
    <div class="splash-form"><label>Splash source<select bind:value={sourceAssetId}><option value="">Sélectionner un asset</option>{#each assets as asset}<option value={asset.id}>{asset.name}</option>{/each}</select></label><label>Splash name (optional)<input bind:value={displayName} placeholder="Splash animation" /></label><div class="actions"><button onclick={() => onorbit(sourceAssetId, displayName || undefined)} disabled={!sourceAssetId}>Use as splash</button></div></div>
  </div>
</section>
<style>
  section{display:grid;gap:13px}.heading,.splash-head{display:flex;justify-content:space-between;align-items:center;gap:12px}.heading span,.splash-head span{color:#35d9ff;font-size:.65rem;font-weight:800;letter-spacing:.14em;text-transform:uppercase}.heading h2,.splash-head h3{margin:3px 0}.upload,.actions button,.preview-button{background:#087fa5;color:white;border:1px solid #35d9ff;border-radius:8px;padding:8px 11px}.library{display:grid;grid-template-columns:repeat(auto-fill,minmax(150px,1fr));gap:9px}.library article{display:grid;gap:6px;padding:9px;border:1px solid #244858;border-radius:11px;background:#091620}.thumb{height:66px;display:grid;place-items:center;border-radius:7px;background:radial-gradient(circle,#143c4f,#061019);color:#4eddfb;font-size:1.5rem}.thumb img{width:100%;height:100%;object-fit:cover;border-radius:7px}.library small,.preset-card small{color:#819baa;font-size:.68rem}.library article>div:last-child{display:flex;gap:5px}.library label,.library button{padding:5px 7px;border:1px solid #35566b;border-radius:6px;background:#102630;color:#d7eaf3;font-size:.7rem}.splash{display:grid;gap:10px;padding-top:4px;border-top:1px solid #203746}.preset-list{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:8px}.preset-card{display:grid;grid-template-columns:112px minmax(0,1fr);align-items:center;gap:11px;padding:9px;border:1px solid #244858;border-radius:11px;background:#091620}.preset-thumb{width:112px;aspect-ratio:960/376;overflow:hidden;border-radius:7px;background:#061019;display:grid;place-items:center;color:#4eddfb}.preset-thumb img{width:100%;height:100%;object-fit:cover}.preset-card>div:last-child{display:grid;gap:3px}.splash-form{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr) auto;gap:8px;align-items:end}.splash-form label{display:grid;gap:4px;color:#91a8b8;font-size:.72rem}.actions{display:flex}.actions button:disabled,.preview-button:disabled{opacity:.5}select,input{width:100%}@media(max-width:760px){.splash-form{grid-template-columns:1fr}.actions button{width:100%}.preset-card{grid-template-columns:90px minmax(0,1fr)}.preset-thumb{width:90px}}
</style>
