<script lang="ts">
  import MediaCard from './MediaCard.svelte';
  export type Preset = { id: string; name: string; source_asset_id: string; settings: { fps: number; speed_seconds: number } };
  export type Asset = { id: string; name: string; kind?: string; format?: string; revision?: number; width?: number; height?: number };
  let { assets = [], presets = [], onorbit, onpreview, onupload, onreplace, ondelete }: { assets?: Asset[]; presets?: Preset[]; onorbit: (sourceAssetId: string, displayName?: string) => void; onpreview: () => void; onupload?: (files: File[]) => void; onreplace?: (id: string, file: File) => void; ondelete?: (id: string) => void } = $props();
  let sourceAssetId = $state('');
  let displayName = $state('');
  let failedImages = $state(new Set<string>());
</script>
<section aria-label="Bibliothèque média"><div class="heading"><div><span>Assets</span><h2>Media Library</h2></div>{#if onupload}<label class="upload">Upload<input type="file" multiple hidden onchange={(event) => onupload?.([...(event.currentTarget.files ?? [])])} /></label>{/if}</div>
  <div class="library">{#each assets as asset}<article><div class="thumb">{#if asset.kind === 'image' && !failedImages.has(asset.id)}<img src={`/api/media/${asset.id}/file`} alt={asset.name} onerror={() => failedImages = new Set([...failedImages, asset.id])} />{:else}{asset.kind === 'image' ? '▧' : '▶'}{/if}</div><strong>{asset.name}</strong><small>{asset.format ?? 'asset'}{asset.width ? ` · ${asset.width}×${asset.height}` : ''} · r{asset.revision ?? 1}</small><div>{#if onreplace}<label>Replace<input type="file" hidden onchange={(event) => event.currentTarget.files?.[0] && onreplace?.(asset.id, event.currentTarget.files[0])} /></label>{/if}{#if ondelete}<button onclick={() => ondelete?.(asset.id)}>Delete</button>{/if}</div></article>{/each}</div>
  <div class="cards"><h3>Splash animation</h3>{#each presets as preset}<MediaCard title={preset.id === 'orbit' && preset.name === 'Orbit' ? 'Splash animation' : preset.name} detail={`Source ${preset.source_asset_id} · ${preset.settings.fps} FPS · ${preset.settings.speed_seconds}s`} />{/each}
  <label>Splash source <select bind:value={sourceAssetId}><option value="">Sélectionner un asset</option>{#each assets as asset}<option value={asset.id}>{asset.name}</option>{/each}</select></label>
  <label>Splash name (optional) <input bind:value={displayName} placeholder="Splash animation" /></label>
  <div class="actions"><button onclick={() => onorbit(sourceAssetId, displayName || undefined)} disabled={!sourceAssetId}>Use as splash</button><button onclick={onpreview} disabled={!presets.some((preset) => preset.id === 'orbit')}>Preview splash</button></div>
</div></section>
<style>section,.cards{display:grid;gap:12px}.heading{display:flex;justify-content:space-between;align-items:center}.heading span{color:#35d9ff;font-size:.68rem;font-weight:800;letter-spacing:.14em;text-transform:uppercase}.heading h2{margin:3px 0}.upload,.actions button{background:#087fa5;color:white;border:1px solid #35d9ff;border-radius:8px;padding:9px 12px}.library{display:grid;grid-template-columns:repeat(auto-fill,minmax(170px,1fr));gap:10px}.library article{display:grid;gap:7px;padding:10px;border:1px solid #244858;border-radius:12px;background:#091620}.thumb{height:72px;display:grid;place-items:center;border-radius:8px;background:radial-gradient(circle,#143c4f,#061019);color:#4eddfb;font-size:1.6rem}.thumb img{width:100%;height:100%;object-fit:cover;border-radius:8px}.library small{color:#819baa}.library article>div:last-child{display:flex;gap:6px}.library label,.library button{padding:5px 7px;border:1px solid #35566b;border-radius:6px;background:#102630;color:#d7eaf3;font-size:.7rem}.actions{display:flex;gap:8px;flex-wrap:wrap}.actions button{justify-self:start}.actions button:disabled{opacity:.5}select,input{width:100%}</style>
