<script lang="ts">
  import MediaCard from './MediaCard.svelte';
  import MediaLibrary, { type Preset } from './MediaLibrary.svelte';
  type Event = { mode?: 'playing'|'incoming'|'landed'|'offline'|'idle'; title?: string; poster_url?: string; progress_pct?: number; eta_minutes?: number; speed_bytes_s?: number; provider_chain?: string[] };
  let { event = {}, assets = [], presets = [], onorbit, onpreview, onupload, onreplace, ondelete }: { event?: Event; assets?: { id: string; name: string; kind?: string; format?: string; revision?: number; width?: number; height?: number }[]; presets?: Preset[]; onorbit: (sourceAssetId: string, displayName?: string) => void; onpreview: () => void; onupload?: (files: File[]) => void; onreplace?: (id: string, file: File) => void; ondelete?: (id: string) => void } = $props();
  const demo: Event = { mode: 'playing', title: 'Sample media — Offline demo', progress_pct: 64, provider_chain: ['Jellyfin · demo'] };
  const current = $derived(event.mode && event.mode !== 'idle' ? event : demo);
  const incoming = $derived(current.mode === 'incoming' ? current : { title: 'The Expanse · S02E04', progress_pct: 82, eta_minutes: 12, speed_bytes_s: 18_400_000, provider_chain: ['Sonarr', 'qBittorrent'] });
</script>
<section class="dashboard"><div class="live"><div class="playing"><span>Now</span><h2>Lecture en cours</h2><MediaCard title={current.title ?? 'Aucun média'} detail={`${current.provider_chain?.join(' + ') ?? 'Media agrégé'} · ${current.mode ?? 'offline'}`} poster={current.poster_url} progress={current.progress_pct} /></div><div class="incoming"><span>Queue</span><h2>À venir</h2><MediaCard title={incoming.title ?? 'À venir'} detail={`${incoming.provider_chain?.join(' + ')} · ETA ${incoming.eta_minutes ?? 12} min · ${Math.round((incoming.speed_bytes_s ?? 18_400_000) / 1_000_000)} MB/s`} progress={incoming.progress_pct} /></div></div><MediaLibrary {assets} {presets} {onorbit} {onpreview} {onupload} {onreplace} {ondelete} /></section>
<style>.dashboard{display:grid;gap:20px}.live{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.playing,.incoming{display:grid;gap:8px;padding:15px;border:1px solid #263f52;border-radius:16px;background:linear-gradient(145deg,#0d1c29,#09151f);box-shadow:0 14px 34px #0003}.playing>span,.incoming>span{color:#35d9ff;font-size:.65rem;font-weight:800;letter-spacing:.14em;text-transform:uppercase}.dashboard h2{margin:0}@media(max-width:760px){.live{grid-template-columns:1fr}}</style>
